# fly.toml app configuration file for the Django web application
# This file should be in your gph-site root directory.

app = 'koreapuzzlehunt'
primary_region = 'nrt'

[build]
  builder = "paketobuildpacks/builder:base"
  [build.args]
    BP_CPYTHON_VERSION = "3.11.4"

[deploy]
  release_command = "sh -c 'python manage.py collectstatic --noinput && python manage.py migrate'"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  # cold start를 방지하기 위하여 이 수치를 1로 바꿀 수 있음.
  processes = ['app']
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthcheck"
    protocol = "http"

[env]
  DATABASE_HOST = "textpuzzlehunt-db.internal"

[processes]
  app = "gunicorn -c gph/gunicorn.py --log-file - gph.wsgi"
