# Generated by Django 4.2.15 on 2025-09-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "puzzles",
            "0006_alter_answersubmission_options_alter_erratum_options_and_more",
        ),
    ]

    operations = []
