# Generated by Django 4.2.15 on 2025-09-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0008_alter_answersubmission_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CannedHint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hint_id", models.CharField(max_length=255, verbose_name="Hint ID")),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puzzles.puzzle",
                        verbose_name="퍼즐",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="puzzles.team",
                        verbose_name="팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "canned hint unlock",
                "verbose_name_plural": "canned hint unlocks",
                "unique_together": {("team", "puzzle", "hint_id")},
            },
        ),
    ]
