# Generated by Django 4.2.15 on 2025-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0009_cannedhint"),
    ]

    operations = [
        migrations.AddField(
            model_name="cannedhint",
            name="opened_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="opened datetime"
            ),
        ),
    ]
