# Generated by Django 4.2.15 on 2025-09-13 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0010_cannedhint_opened_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cannedhint",
            name="opened_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 9, 13, 19, 29, 43, 480628),
                verbose_name="opened datetime",
            ),
            preserve_default=False,
        ),
    ]
