# Generated by Django 4.2.15 on 2025-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0011_alter_cannedhint_opened_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="hunt_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text='The time this team clicked the "Start Hunt" button.',
                null=True,
                verbose_name="Hunt Start Time",
            ),
        ),
    ]
