# Generated by Django 4.2.15 on 2025-09-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0012_team_hunt_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team", old_name="hunt_start_time", new_name="team_start_time",
        ),
    ]
